"""Constants matching BasicPitchConstants.h and related headers."""

# From BasicPitchConstants.h
NUM_HARMONICS = 8
NUM_FREQ_IN = 264
NUM_FREQ_OUT = 88
BASIC_PITCH_SAMPLE_RATE = 22050.0

MIDI_OFFSET = 21
FFT_HOP = 256
AUDIO_SAMPLE_RATE = 22050
MAX_NOTE_IDX = 87
AUDIO_WINDOW_LENGTH = 2  # duration in seconds of training examples

# Lowest key on a piano
ANNOTATIONS_BASE_FREQUENCY = 27.5
CONTOURS_BINS_PER_SEMITONE = 3

MIN_MIDI_NOTE = 21
MAX_MIDI_NOTE = 108

# From Notes.cpp - energy threshold
ENERGY_THRESHOLD = 11

# From BasicPitchCNN.h - lookahead constants
LOOKAHEAD_CNN_CONTOUR = 3
LOOKAHEAD_CNN_NOTE = 6
LOOKAHEAD_CNN_ONSET_INPUT = 2
LOOKAHEAD_CNN_ONSET_OUTPUT = 1
TOTAL_LOOKAHEAD = LOOKAHEAD_CNN_CONTOUR + LOOKAHEAD_CNN_NOTE + LOOKAHEAD_CNN_ONSET_OUTPUT

# Circular buffer sizes
NUM_CONTOUR_STORED = TOTAL_LOOKAHEAD - LOOKAHEAD_CNN_CONTOUR + 1
NUM_NOTE_STORED = TOTAL_LOOKAHEAD - (LOOKAHEAD_CNN_CONTOUR + LOOKAHEAD_CNN_NOTE) + 1
NUM_CONCAT2_STORED = LOOKAHEAD_CNN_CONTOUR + LOOKAHEAD_CNN_NOTE - LOOKAHEAD_CNN_ONSET_INPUT + 1

# From Notes.cpp - pitch bend tolerance
NUM_BINS_TOLERANCE = 25
PITCH_BEND_STD = 5.0
